channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - earthengine-api=0.1.236
  - google-api-python-client==1.12.8
  - gdal=2.3.3
  - pandas=0.24.2
  - geopandas=0.4.1
  - numpy
  - matplotlib
  - pillow
  - pytz
  - scikit-image
  - scikit-learn
  - shapely
  - scipy
  - astropy
  - spyder
  - notebook
